// Livepeer Payments v1 — PayeeDaemon service.
//
// The PayeeDaemon runs next to a payee application (a specialized PayeeApp —
// e.g., a WorkerNode or a Livepeer orchestrator). It validates tickets,
// tracks per-sender balances, and redeems winning tickets on-chain via the
// TicketBroker.
//
// This service is mounted only when the daemon is started with
// `--mode=receiver`. Calls to it in sender mode return UNIMPLEMENTED.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/payments/v1/payee_daemon.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionResponse_Outcome int32

const (
	OpenSessionResponse_OUTCOME_UNSPECIFIED  OpenSessionResponse_Outcome = 0
	OpenSessionResponse_OUTCOME_OPENED       OpenSessionResponse_Outcome = 1
	OpenSessionResponse_OUTCOME_ALREADY_OPEN OpenSessionResponse_Outcome = 2
)

// Enum value maps for OpenSessionResponse_Outcome.
var (
	OpenSessionResponse_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_OPENED",
		2: "OUTCOME_ALREADY_OPEN",
	}
	OpenSessionResponse_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":  0,
		"OUTCOME_OPENED":       1,
		"OUTCOME_ALREADY_OPEN": 2,
	}
)

func (x OpenSessionResponse_Outcome) Enum() *OpenSessionResponse_Outcome {
	p := new(OpenSessionResponse_Outcome)
	*p = x
	return p
}

func (x OpenSessionResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenSessionResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_payee_daemon_proto_enumTypes[0].Descriptor()
}

func (OpenSessionResponse_Outcome) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_payee_daemon_proto_enumTypes[0]
}

func (x OpenSessionResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenSessionResponse_Outcome.Descriptor instead.
func (OpenSessionResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{9, 0}
}

type PayeeDaemonCloseSessionResponse_Outcome int32

const (
	PayeeDaemonCloseSessionResponse_OUTCOME_UNSPECIFIED    PayeeDaemonCloseSessionResponse_Outcome = 0
	PayeeDaemonCloseSessionResponse_OUTCOME_CLOSED         PayeeDaemonCloseSessionResponse_Outcome = 1
	PayeeDaemonCloseSessionResponse_OUTCOME_ALREADY_CLOSED PayeeDaemonCloseSessionResponse_Outcome = 2
)

// Enum value maps for PayeeDaemonCloseSessionResponse_Outcome.
var (
	PayeeDaemonCloseSessionResponse_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_CLOSED",
		2: "OUTCOME_ALREADY_CLOSED",
	}
	PayeeDaemonCloseSessionResponse_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":    0,
		"OUTCOME_CLOSED":         1,
		"OUTCOME_ALREADY_CLOSED": 2,
	}
)

func (x PayeeDaemonCloseSessionResponse_Outcome) Enum() *PayeeDaemonCloseSessionResponse_Outcome {
	p := new(PayeeDaemonCloseSessionResponse_Outcome)
	*p = x
	return p
}

func (x PayeeDaemonCloseSessionResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayeeDaemonCloseSessionResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_payee_daemon_proto_enumTypes[1].Descriptor()
}

func (PayeeDaemonCloseSessionResponse_Outcome) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_payee_daemon_proto_enumTypes[1]
}

func (x PayeeDaemonCloseSessionResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayeeDaemonCloseSessionResponse_Outcome.Descriptor instead.
func (PayeeDaemonCloseSessionResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{19, 0}
}

type GetRedemptionStatusResponse_Status int32

const (
	GetRedemptionStatusResponse_STATUS_UNSPECIFIED GetRedemptionStatusResponse_Status = 0
	GetRedemptionStatusResponse_STATUS_QUEUED      GetRedemptionStatusResponse_Status = 1
	GetRedemptionStatusResponse_STATUS_SUBMITTED   GetRedemptionStatusResponse_Status = 2
	GetRedemptionStatusResponse_STATUS_CONFIRMED   GetRedemptionStatusResponse_Status = 3
	GetRedemptionStatusResponse_STATUS_FAILED      GetRedemptionStatusResponse_Status = 4
)

// Enum value maps for GetRedemptionStatusResponse_Status.
var (
	GetRedemptionStatusResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_QUEUED",
		2: "STATUS_SUBMITTED",
		3: "STATUS_CONFIRMED",
		4: "STATUS_FAILED",
	}
	GetRedemptionStatusResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_QUEUED":      1,
		"STATUS_SUBMITTED":   2,
		"STATUS_CONFIRMED":   3,
		"STATUS_FAILED":      4,
	}
)

func (x GetRedemptionStatusResponse_Status) Enum() *GetRedemptionStatusResponse_Status {
	p := new(GetRedemptionStatusResponse_Status)
	*p = x
	return p
}

func (x GetRedemptionStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRedemptionStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_livepeer_payments_v1_payee_daemon_proto_enumTypes[2].Descriptor()
}

func (GetRedemptionStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_livepeer_payments_v1_payee_daemon_proto_enumTypes[2]
}

func (x GetRedemptionStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRedemptionStatusResponse_Status.Descriptor instead.
func (GetRedemptionStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{24, 0}
}

type GetQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ETH address of the sender asking for a quote.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Capability the sender intends to purchase. The daemon maps this to the
	// `PriceInfo.capability` uint32 at the wire boundary. One capability may
	// host many offerings; the response lists them all.
	Capability    string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuoteRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GetQuoteRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type GetQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single TicketParams for this (sender, capability). Face value is sized
	// to cover the most expensive offering on this capability so one session
	// covers the whole offering set without re-keying RecipientRandHash per
	// offering.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// Per-offering pricing. Ordered by offering id for deterministic comparison
	// on the bridge's quote-refresh cycle. Empty iff the daemon has no
	// offerings configured for this capability (caller should treat as NotFound).
	OfferingPrices []*OfferingPrice `protobuf:"bytes,2,rep,name=offering_prices,json=offeringPrices,proto3" json:"offering_prices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteResponse) GetTicketParams() *TicketParams {
	if x != nil {
		return x.TicketParams
	}
	return nil
}

func (x *GetQuoteResponse) GetOfferingPrices() []*OfferingPrice {
	if x != nil {
		return x.OfferingPrices
	}
	return nil
}

type GetTicketParamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ETH address of the sender that will sign the ticket.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// ETH address of the intended recipient. Must match the receiver daemon's
	// configured recipient when provided.
	Recipient []byte `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Target spend / expected-value request in wei, big-endian bytes, for the
	// quote-free sender/payee flow. The receiver may return a larger
	// TicketParams.face_value when redemption economics require a redeemable
	// winning ticket, paired with a lower win probability so expected spend stays
	// aligned with this request.
	FaceValue []byte `protobuf:"bytes,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Optional capability / offering metadata for logging and future metrics.
	Capability    string `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`
	Offering      string `protobuf:"bytes,5,opt,name=offering,proto3" json:"offering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketParamsRequest) Reset() {
	*x = GetTicketParamsRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketParamsRequest) ProtoMessage() {}

func (x *GetTicketParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketParamsRequest.ProtoReflect.Descriptor instead.
func (*GetTicketParamsRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetTicketParamsRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GetTicketParamsRequest) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *GetTicketParamsRequest) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *GetTicketParamsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *GetTicketParamsRequest) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

type GetTicketParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketParams  *TicketParams          `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketParamsResponse) Reset() {
	*x = GetTicketParamsResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketParamsResponse) ProtoMessage() {}

func (x *GetTicketParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketParamsResponse.ProtoReflect.Descriptor instead.
func (*GetTicketParamsResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetTicketParamsResponse) GetTicketParams() *TicketParams {
	if x != nil {
		return x.TicketParams
	}
	return nil
}

// OfferingPrice pairs an offering identifier with its wei-per-work-unit price.
// Shared between GetQuoteResponse and ListCapabilitiesResponse so the two
// surfaces cannot drift.
type OfferingPrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offering identifier, e.g. "llama-3.3-70b". Must match the offering string the
	// bridge uses when resolving a request to a node.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Price for one work unit (see CapabilityEntry.work_unit for the meaning
	// of "unit" on this capability).
	PriceInfo     *PriceInfo `protobuf:"bytes,2,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferingPrice) Reset() {
	*x = OfferingPrice{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferingPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferingPrice) ProtoMessage() {}

func (x *OfferingPrice) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferingPrice.ProtoReflect.Descriptor instead.
func (*OfferingPrice) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *OfferingPrice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OfferingPrice) GetPriceInfo() *PriceInfo {
	if x != nil {
		return x.PriceInfo
	}
	return nil
}

type ListCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesRequest) Reset() {
	*x = ListCapabilitiesRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesRequest) ProtoMessage() {}

func (x *ListCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{5}
}

type ListCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full capability catalog as parsed by the daemon at startup. Ordered
	// by capability string, then offering id, for deterministic comparison.
	Capabilities  []*CapabilityEntry `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesResponse) Reset() {
	*x = ListCapabilitiesResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesResponse) ProtoMessage() {}

func (x *ListCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ListCapabilitiesResponse) GetCapabilities() []*CapabilityEntry {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CapabilityEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Capability string in the canonical form `openai:<uri-path>` for the
	// OpenAI module family; other modules use their own domain prefix
	// (e.g. `transcoding:...`). Opaque to the daemon.
	Capability string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Work-unit identifier for observability ("token", "audio_second",
	// "image_step_megapixel", "character", ...). The daemon treats work
	// units as opaque int64 — this field is metadata for the worker /
	// bridge.
	WorkUnit string `protobuf:"bytes,2,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	// Offerings served on this capability, with their configured prices.
	Offerings     []*OfferingPrice `protobuf:"bytes,3,rep,name=offerings,proto3" json:"offerings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityEntry) Reset() {
	*x = CapabilityEntry{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityEntry) ProtoMessage() {}

func (x *CapabilityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityEntry.ProtoReflect.Descriptor instead.
func (*CapabilityEntry) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityEntry) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityEntry) GetWorkUnit() string {
	if x != nil {
		return x.WorkUnit
	}
	return ""
}

func (x *CapabilityEntry) GetOfferings() []*OfferingPrice {
	if x != nil {
		return x.Offerings
	}
	return nil
}

type OpenSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque session identifier chosen by the payee app.
	WorkId string `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Capability the session is opened against.
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// Offering the session is opened against.
	Offering string `protobuf:"bytes,3,opt,name=offering,proto3" json:"offering,omitempty"`
	// Authoritative price per work unit for this session (wei, big-endian
	// bytes).
	PricePerWorkUnitWei []byte `protobuf:"bytes,4,opt,name=price_per_work_unit_wei,json=pricePerWorkUnitWei,proto3" json:"price_per_work_unit_wei,omitempty"`
	// Work-unit identifier for this session ("token", "second", ...).
	WorkUnit      string `protobuf:"bytes,5,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *OpenSessionRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *OpenSessionRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *OpenSessionRequest) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

func (x *OpenSessionRequest) GetPricePerWorkUnitWei() []byte {
	if x != nil {
		return x.PricePerWorkUnitWei
	}
	return nil
}

func (x *OpenSessionRequest) GetWorkUnit() string {
	if x != nil {
		return x.WorkUnit
	}
	return ""
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Outcome       OpenSessionResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=livepeer.payments.v1.OpenSessionResponse_Outcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *OpenSessionResponse) GetOutcome() OpenSessionResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return OpenSessionResponse_OUTCOME_UNSPECIFIED
}

type ProcessPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire-format `livepeer.payments.v1.Payment` bytes, exactly as received
	// from the sender.
	PaymentBytes []byte `protobuf:"bytes,1,opt,name=payment_bytes,json=paymentBytes,proto3" json:"payment_bytes,omitempty"`
	// Opaque session identifier chosen by the payee app. The daemon requires
	// a previously-opened session with this id.
	WorkId        string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessPaymentRequest) GetPaymentBytes() []byte {
	if x != nil {
		return x.PaymentBytes
	}
	return nil
}

func (x *ProcessPaymentRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type ProcessPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender address extracted from the validated payment.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Expected value credited to the sender's balance by this payment (wei,
	// big-endian bytes).
	CreditedEv []byte `protobuf:"bytes,2,opt,name=credited_ev,json=creditedEv,proto3" json:"credited_ev,omitempty"`
	// New balance after crediting (wei, big-endian bytes).
	Balance []byte `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	// Number of tickets in this payment that were identified as winners and
	// queued for on-chain redemption.
	WinnersQueued int32 `protobuf:"varint,4,opt,name=winners_queued,json=winnersQueued,proto3" json:"winners_queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessPaymentResponse) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ProcessPaymentResponse) GetCreditedEv() []byte {
	if x != nil {
		return x.CreditedEv
	}
	return nil
}

func (x *ProcessPaymentResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *ProcessPaymentResponse) GetWinnersQueued() int32 {
	if x != nil {
		return x.WinnersQueued
	}
	return 0
}

type DebitBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender whose balance is being debited.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Work session whose balance is being debited.
	WorkId string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Number of work units actually consumed.
	WorkUnits int64 `protobuf:"varint,3,opt,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	// Monotonic debit sequence number within the session. Retries of the same
	// logical debit must reuse the same value.
	DebitSeq      uint64 `protobuf:"varint,4,opt,name=debit_seq,json=debitSeq,proto3" json:"debit_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitBalanceRequest) Reset() {
	*x = DebitBalanceRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitBalanceRequest) ProtoMessage() {}

func (x *DebitBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitBalanceRequest.ProtoReflect.Descriptor instead.
func (*DebitBalanceRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *DebitBalanceRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *DebitBalanceRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *DebitBalanceRequest) GetWorkUnits() int64 {
	if x != nil {
		return x.WorkUnits
	}
	return 0
}

func (x *DebitBalanceRequest) GetDebitSeq() uint64 {
	if x != nil {
		return x.DebitSeq
	}
	return 0
}

type DebitBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New balance after debit (wei, big-endian bytes). Negative values indicate
	// overdraft; callers should stop serving work when this happens.
	Balance       []byte `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitBalanceResponse) Reset() {
	*x = DebitBalanceResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitBalanceResponse) ProtoMessage() {}

func (x *DebitBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitBalanceResponse.ProtoReflect.Descriptor instead.
func (*DebitBalanceResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *DebitBalanceResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type SufficientBalanceRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Sender []byte                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Minimum required runway in session-priced work units.
	MinWorkUnits  int64 `protobuf:"varint,3,opt,name=min_work_units,json=minWorkUnits,proto3" json:"min_work_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SufficientBalanceRequest) Reset() {
	*x = SufficientBalanceRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SufficientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SufficientBalanceRequest) ProtoMessage() {}

func (x *SufficientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SufficientBalanceRequest.ProtoReflect.Descriptor instead.
func (*SufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *SufficientBalanceRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SufficientBalanceRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *SufficientBalanceRequest) GetMinWorkUnits() int64 {
	if x != nil {
		return x.MinWorkUnits
	}
	return 0
}

type SufficientBalanceResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Sufficient bool                   `protobuf:"varint,1,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	// Current balance (wei, big-endian bytes).
	Balance       []byte `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SufficientBalanceResponse) Reset() {
	*x = SufficientBalanceResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SufficientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SufficientBalanceResponse) ProtoMessage() {}

func (x *SufficientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SufficientBalanceResponse.ProtoReflect.Descriptor instead.
func (*SufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *SufficientBalanceResponse) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

func (x *SufficientBalanceResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        []byte                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *GetBalanceRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GetBalanceRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       []byte                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *GetBalanceResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type PayeeDaemonCloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        []byte                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayeeDaemonCloseSessionRequest) Reset() {
	*x = PayeeDaemonCloseSessionRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayeeDaemonCloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayeeDaemonCloseSessionRequest) ProtoMessage() {}

func (x *PayeeDaemonCloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayeeDaemonCloseSessionRequest.ProtoReflect.Descriptor instead.
func (*PayeeDaemonCloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *PayeeDaemonCloseSessionRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PayeeDaemonCloseSessionRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type PayeeDaemonCloseSessionResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Outcome       PayeeDaemonCloseSessionResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=livepeer.payments.v1.PayeeDaemonCloseSessionResponse_Outcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayeeDaemonCloseSessionResponse) Reset() {
	*x = PayeeDaemonCloseSessionResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayeeDaemonCloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayeeDaemonCloseSessionResponse) ProtoMessage() {}

func (x *PayeeDaemonCloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayeeDaemonCloseSessionResponse.ProtoReflect.Descriptor instead.
func (*PayeeDaemonCloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *PayeeDaemonCloseSessionResponse) GetOutcome() PayeeDaemonCloseSessionResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return PayeeDaemonCloseSessionResponse_OUTCOME_UNSPECIFIED
}

type ListPendingRedemptionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter to tickets queued on or after this Unix epoch seconds.
	Since         int64 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRedemptionsRequest) Reset() {
	*x = ListPendingRedemptionsRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRedemptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRedemptionsRequest) ProtoMessage() {}

func (x *ListPendingRedemptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRedemptionsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingRedemptionsRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *ListPendingRedemptionsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type ListPendingRedemptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redemptions   []*PendingRedemption   `protobuf:"bytes,1,rep,name=redemptions,proto3" json:"redemptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRedemptionsResponse) Reset() {
	*x = ListPendingRedemptionsResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRedemptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRedemptionsResponse) ProtoMessage() {}

func (x *ListPendingRedemptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRedemptionsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingRedemptionsResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *ListPendingRedemptionsResponse) GetRedemptions() []*PendingRedemption {
	if x != nil {
		return x.Redemptions
	}
	return nil
}

type PendingRedemption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deterministic ticket identifier (keccak256 of the ticket hash).
	TicketHash []byte `protobuf:"bytes,1,opt,name=ticket_hash,json=ticketHash,proto3" json:"ticket_hash,omitempty"`
	Sender     []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Face value (wei, big-endian bytes).
	FaceValue []byte `protobuf:"bytes,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Unix epoch seconds when the ticket was queued.
	QueuedAt int64 `protobuf:"varint,4,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	// Number of on-chain redemption attempts made so far.
	Attempts      int32 `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRedemption) Reset() {
	*x = PendingRedemption{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRedemption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRedemption) ProtoMessage() {}

func (x *PendingRedemption) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRedemption.ProtoReflect.Descriptor instead.
func (*PendingRedemption) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *PendingRedemption) GetTicketHash() []byte {
	if x != nil {
		return x.TicketHash
	}
	return nil
}

func (x *PendingRedemption) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PendingRedemption) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *PendingRedemption) GetQueuedAt() int64 {
	if x != nil {
		return x.QueuedAt
	}
	return 0
}

func (x *PendingRedemption) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type GetRedemptionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketHash    []byte                 `protobuf:"bytes,1,opt,name=ticket_hash,json=ticketHash,proto3" json:"ticket_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedemptionStatusRequest) Reset() {
	*x = GetRedemptionStatusRequest{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedemptionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedemptionStatusRequest) ProtoMessage() {}

func (x *GetRedemptionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedemptionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRedemptionStatusRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *GetRedemptionStatusRequest) GetTicketHash() []byte {
	if x != nil {
		return x.TicketHash
	}
	return nil
}

type GetRedemptionStatusResponse struct {
	state  protoimpl.MessageState             `protogen:"open.v1"`
	Status GetRedemptionStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=livepeer.payments.v1.GetRedemptionStatusResponse_Status" json:"status,omitempty"`
	// Transaction hash once submitted; empty before then.
	TxHash []byte `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Non-empty when status is STATUS_FAILED — operator-actionable message.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedemptionStatusResponse) Reset() {
	*x = GetRedemptionStatusResponse{}
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedemptionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedemptionStatusResponse) ProtoMessage() {}

func (x *GetRedemptionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payee_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedemptionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRedemptionStatusResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *GetRedemptionStatusResponse) GetStatus() GetRedemptionStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetRedemptionStatusResponse_STATUS_UNSPECIFIED
}

func (x *GetRedemptionStatusResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *GetRedemptionStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_livepeer_payments_v1_payee_daemon_proto protoreflect.FileDescriptor

const file_livepeer_payments_v1_payee_daemon_proto_rawDesc = "" +
	"\n" +
	"'livepeer/payments/v1/payee_daemon.proto\x12\x14livepeer.payments.v1\x1a livepeer/payments/v1/types.proto\"I\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\"\xa9\x01\n" +
	"\x10GetQuoteResponse\x12G\n" +
	"\rticket_params\x18\x01 \x01(\v2\".livepeer.payments.v1.TicketParamsR\fticketParams\x12L\n" +
	"\x0foffering_prices\x18\x02 \x03(\v2#.livepeer.payments.v1.OfferingPriceR\x0eofferingPrices\"\xa9\x01\n" +
	"\x16GetTicketParamsRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\fR\trecipient\x12\x1d\n" +
	"\n" +
	"face_value\x18\x03 \x01(\fR\tfaceValue\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x05 \x01(\tR\boffering\"b\n" +
	"\x17GetTicketParamsResponse\x12G\n" +
	"\rticket_params\x18\x01 \x01(\v2\".livepeer.payments.v1.TicketParamsR\fticketParams\"_\n" +
	"\rOfferingPrice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"price_info\x18\x02 \x01(\v2\x1f.livepeer.payments.v1.PriceInfoR\tpriceInfo\"\x19\n" +
	"\x17ListCapabilitiesRequest\"}\n" +
	"\x18ListCapabilitiesResponse\x12I\n" +
	"\fcapabilities\x18\x02 \x03(\v2%.livepeer.payments.v1.CapabilityEntryR\fcapabilitiesJ\x04\b\x01\x10\x02R\x10protocol_version\"\x91\x01\n" +
	"\x0fCapabilityEntry\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x1b\n" +
	"\twork_unit\x18\x02 \x01(\tR\bworkUnit\x12A\n" +
	"\tofferings\x18\x03 \x03(\v2#.livepeer.payments.v1.OfferingPriceR\tofferings\"\xbc\x01\n" +
	"\x12OpenSessionRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x03 \x01(\tR\boffering\x124\n" +
	"\x17price_per_work_unit_wei\x18\x04 \x01(\fR\x13pricePerWorkUnitWei\x12\x1b\n" +
	"\twork_unit\x18\x05 \x01(\tR\bworkUnit\"\xb4\x01\n" +
	"\x13OpenSessionResponse\x12K\n" +
	"\aoutcome\x18\x01 \x01(\x0e21.livepeer.payments.v1.OpenSessionResponse.OutcomeR\aoutcome\"P\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eOUTCOME_OPENED\x10\x01\x12\x18\n" +
	"\x14OUTCOME_ALREADY_OPEN\x10\x02\"U\n" +
	"\x15ProcessPaymentRequest\x12#\n" +
	"\rpayment_bytes\x18\x01 \x01(\fR\fpaymentBytes\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\"\x92\x01\n" +
	"\x16ProcessPaymentResponse\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x1f\n" +
	"\vcredited_ev\x18\x02 \x01(\fR\n" +
	"creditedEv\x12\x18\n" +
	"\abalance\x18\x03 \x01(\fR\abalance\x12%\n" +
	"\x0ewinners_queued\x18\x04 \x01(\x05R\rwinnersQueued\"\x82\x01\n" +
	"\x13DebitBalanceRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"work_units\x18\x03 \x01(\x03R\tworkUnits\x12\x1b\n" +
	"\tdebit_seq\x18\x04 \x01(\x04R\bdebitSeq\"0\n" +
	"\x14DebitBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\fR\abalance\"q\n" +
	"\x18SufficientBalanceRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12$\n" +
	"\x0emin_work_units\x18\x03 \x01(\x03R\fminWorkUnits\"U\n" +
	"\x19SufficientBalanceResponse\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x01 \x01(\bR\n" +
	"sufficient\x12\x18\n" +
	"\abalance\x18\x02 \x01(\fR\abalance\"D\n" +
	"\x11GetBalanceRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\fR\abalance\"Q\n" +
	"\x1ePayeeDaemonCloseSessionRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\fR\x06sender\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\"\xce\x01\n" +
	"\x1fPayeeDaemonCloseSessionResponse\x12W\n" +
	"\aoutcome\x18\x01 \x01(\x0e2=.livepeer.payments.v1.PayeeDaemonCloseSessionResponse.OutcomeR\aoutcome\"R\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eOUTCOME_CLOSED\x10\x01\x12\x1a\n" +
	"\x16OUTCOME_ALREADY_CLOSED\x10\x02\"5\n" +
	"\x1dListPendingRedemptionsRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x03R\x05since\"k\n" +
	"\x1eListPendingRedemptionsResponse\x12I\n" +
	"\vredemptions\x18\x01 \x03(\v2'.livepeer.payments.v1.PendingRedemptionR\vredemptions\"\xa4\x01\n" +
	"\x11PendingRedemption\x12\x1f\n" +
	"\vticket_hash\x18\x01 \x01(\fR\n" +
	"ticketHash\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12\x1d\n" +
	"\n" +
	"face_value\x18\x03 \x01(\fR\tfaceValue\x12\x1b\n" +
	"\tqueued_at\x18\x04 \x01(\x03R\bqueuedAt\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\"=\n" +
	"\x1aGetRedemptionStatusRequest\x12\x1f\n" +
	"\vticket_hash\x18\x01 \x01(\fR\n" +
	"ticketHash\"\x92\x02\n" +
	"\x1bGetRedemptionStatusResponse\x12P\n" +
	"\x06status\x18\x01 \x01(\x0e28.livepeer.payments.v1.GetRedemptionStatusResponse.StatusR\x06status\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\x01\x12\x14\n" +
	"\x10STATUS_SUBMITTED\x10\x02\x12\x14\n" +
	"\x10STATUS_CONFIRMED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x042\xd9\t\n" +
	"\vPayeeDaemon\x12Y\n" +
	"\bGetQuote\x12%.livepeer.payments.v1.GetQuoteRequest\x1a&.livepeer.payments.v1.GetQuoteResponse\x12n\n" +
	"\x0fGetTicketParams\x12,.livepeer.payments.v1.GetTicketParamsRequest\x1a-.livepeer.payments.v1.GetTicketParamsResponse\x12q\n" +
	"\x10ListCapabilities\x12-.livepeer.payments.v1.ListCapabilitiesRequest\x1a..livepeer.payments.v1.ListCapabilitiesResponse\x12b\n" +
	"\vOpenSession\x12(.livepeer.payments.v1.OpenSessionRequest\x1a).livepeer.payments.v1.OpenSessionResponse\x12k\n" +
	"\x0eProcessPayment\x12+.livepeer.payments.v1.ProcessPaymentRequest\x1a,.livepeer.payments.v1.ProcessPaymentResponse\x12e\n" +
	"\fDebitBalance\x12).livepeer.payments.v1.DebitBalanceRequest\x1a*.livepeer.payments.v1.DebitBalanceResponse\x12t\n" +
	"\x11SufficientBalance\x12..livepeer.payments.v1.SufficientBalanceRequest\x1a/.livepeer.payments.v1.SufficientBalanceResponse\x12_\n" +
	"\n" +
	"GetBalance\x12'.livepeer.payments.v1.GetBalanceRequest\x1a(.livepeer.payments.v1.GetBalanceResponse\x12{\n" +
	"\fCloseSession\x124.livepeer.payments.v1.PayeeDaemonCloseSessionRequest\x1a5.livepeer.payments.v1.PayeeDaemonCloseSessionResponse\x12\x83\x01\n" +
	"\x16ListPendingRedemptions\x123.livepeer.payments.v1.ListPendingRedemptionsRequest\x1a4.livepeer.payments.v1.ListPendingRedemptionsResponse\x12z\n" +
	"\x13GetRedemptionStatus\x120.livepeer.payments.v1.GetRedemptionStatusRequest\x1a1.livepeer.payments.v1.GetRedemptionStatusResponseB\x89\x02\n" +
	"\x18com.livepeer.payments.v1B\x10PayeeDaemonProtoP\x01Zigithub.com/Cloud-SPE/livepeer-modules-project/payment-daemon/proto/gen/go/livepeer/payments/v1;paymentsv1\xa2\x02\x03LPX\xaa\x02\x14Livepeer.Payments.V1\xca\x02\x14Livepeer\\Payments\\V1\xe2\x02 Livepeer\\Payments\\V1\\GPBMetadata\xea\x02\x16Livepeer::Payments::V1b\x06proto3"

var (
	file_livepeer_payments_v1_payee_daemon_proto_rawDescOnce sync.Once
	file_livepeer_payments_v1_payee_daemon_proto_rawDescData []byte
)

func file_livepeer_payments_v1_payee_daemon_proto_rawDescGZIP() []byte {
	file_livepeer_payments_v1_payee_daemon_proto_rawDescOnce.Do(func() {
		file_livepeer_payments_v1_payee_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_payee_daemon_proto_rawDesc), len(file_livepeer_payments_v1_payee_daemon_proto_rawDesc)))
	})
	return file_livepeer_payments_v1_payee_daemon_proto_rawDescData
}

var file_livepeer_payments_v1_payee_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_livepeer_payments_v1_payee_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_livepeer_payments_v1_payee_daemon_proto_goTypes = []any{
	(OpenSessionResponse_Outcome)(0),             // 0: livepeer.payments.v1.OpenSessionResponse.Outcome
	(PayeeDaemonCloseSessionResponse_Outcome)(0), // 1: livepeer.payments.v1.PayeeDaemonCloseSessionResponse.Outcome
	(GetRedemptionStatusResponse_Status)(0),      // 2: livepeer.payments.v1.GetRedemptionStatusResponse.Status
	(*GetQuoteRequest)(nil),                      // 3: livepeer.payments.v1.GetQuoteRequest
	(*GetQuoteResponse)(nil),                     // 4: livepeer.payments.v1.GetQuoteResponse
	(*GetTicketParamsRequest)(nil),               // 5: livepeer.payments.v1.GetTicketParamsRequest
	(*GetTicketParamsResponse)(nil),              // 6: livepeer.payments.v1.GetTicketParamsResponse
	(*OfferingPrice)(nil),                        // 7: livepeer.payments.v1.OfferingPrice
	(*ListCapabilitiesRequest)(nil),              // 8: livepeer.payments.v1.ListCapabilitiesRequest
	(*ListCapabilitiesResponse)(nil),             // 9: livepeer.payments.v1.ListCapabilitiesResponse
	(*CapabilityEntry)(nil),                      // 10: livepeer.payments.v1.CapabilityEntry
	(*OpenSessionRequest)(nil),                   // 11: livepeer.payments.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),                  // 12: livepeer.payments.v1.OpenSessionResponse
	(*ProcessPaymentRequest)(nil),                // 13: livepeer.payments.v1.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),               // 14: livepeer.payments.v1.ProcessPaymentResponse
	(*DebitBalanceRequest)(nil),                  // 15: livepeer.payments.v1.DebitBalanceRequest
	(*DebitBalanceResponse)(nil),                 // 16: livepeer.payments.v1.DebitBalanceResponse
	(*SufficientBalanceRequest)(nil),             // 17: livepeer.payments.v1.SufficientBalanceRequest
	(*SufficientBalanceResponse)(nil),            // 18: livepeer.payments.v1.SufficientBalanceResponse
	(*GetBalanceRequest)(nil),                    // 19: livepeer.payments.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),                   // 20: livepeer.payments.v1.GetBalanceResponse
	(*PayeeDaemonCloseSessionRequest)(nil),       // 21: livepeer.payments.v1.PayeeDaemonCloseSessionRequest
	(*PayeeDaemonCloseSessionResponse)(nil),      // 22: livepeer.payments.v1.PayeeDaemonCloseSessionResponse
	(*ListPendingRedemptionsRequest)(nil),        // 23: livepeer.payments.v1.ListPendingRedemptionsRequest
	(*ListPendingRedemptionsResponse)(nil),       // 24: livepeer.payments.v1.ListPendingRedemptionsResponse
	(*PendingRedemption)(nil),                    // 25: livepeer.payments.v1.PendingRedemption
	(*GetRedemptionStatusRequest)(nil),           // 26: livepeer.payments.v1.GetRedemptionStatusRequest
	(*GetRedemptionStatusResponse)(nil),          // 27: livepeer.payments.v1.GetRedemptionStatusResponse
	(*TicketParams)(nil),                         // 28: livepeer.payments.v1.TicketParams
	(*PriceInfo)(nil),                            // 29: livepeer.payments.v1.PriceInfo
}
var file_livepeer_payments_v1_payee_daemon_proto_depIdxs = []int32{
	28, // 0: livepeer.payments.v1.GetQuoteResponse.ticket_params:type_name -> livepeer.payments.v1.TicketParams
	7,  // 1: livepeer.payments.v1.GetQuoteResponse.offering_prices:type_name -> livepeer.payments.v1.OfferingPrice
	28, // 2: livepeer.payments.v1.GetTicketParamsResponse.ticket_params:type_name -> livepeer.payments.v1.TicketParams
	29, // 3: livepeer.payments.v1.OfferingPrice.price_info:type_name -> livepeer.payments.v1.PriceInfo
	10, // 4: livepeer.payments.v1.ListCapabilitiesResponse.capabilities:type_name -> livepeer.payments.v1.CapabilityEntry
	7,  // 5: livepeer.payments.v1.CapabilityEntry.offerings:type_name -> livepeer.payments.v1.OfferingPrice
	0,  // 6: livepeer.payments.v1.OpenSessionResponse.outcome:type_name -> livepeer.payments.v1.OpenSessionResponse.Outcome
	1,  // 7: livepeer.payments.v1.PayeeDaemonCloseSessionResponse.outcome:type_name -> livepeer.payments.v1.PayeeDaemonCloseSessionResponse.Outcome
	25, // 8: livepeer.payments.v1.ListPendingRedemptionsResponse.redemptions:type_name -> livepeer.payments.v1.PendingRedemption
	2,  // 9: livepeer.payments.v1.GetRedemptionStatusResponse.status:type_name -> livepeer.payments.v1.GetRedemptionStatusResponse.Status
	3,  // 10: livepeer.payments.v1.PayeeDaemon.GetQuote:input_type -> livepeer.payments.v1.GetQuoteRequest
	5,  // 11: livepeer.payments.v1.PayeeDaemon.GetTicketParams:input_type -> livepeer.payments.v1.GetTicketParamsRequest
	8,  // 12: livepeer.payments.v1.PayeeDaemon.ListCapabilities:input_type -> livepeer.payments.v1.ListCapabilitiesRequest
	11, // 13: livepeer.payments.v1.PayeeDaemon.OpenSession:input_type -> livepeer.payments.v1.OpenSessionRequest
	13, // 14: livepeer.payments.v1.PayeeDaemon.ProcessPayment:input_type -> livepeer.payments.v1.ProcessPaymentRequest
	15, // 15: livepeer.payments.v1.PayeeDaemon.DebitBalance:input_type -> livepeer.payments.v1.DebitBalanceRequest
	17, // 16: livepeer.payments.v1.PayeeDaemon.SufficientBalance:input_type -> livepeer.payments.v1.SufficientBalanceRequest
	19, // 17: livepeer.payments.v1.PayeeDaemon.GetBalance:input_type -> livepeer.payments.v1.GetBalanceRequest
	21, // 18: livepeer.payments.v1.PayeeDaemon.CloseSession:input_type -> livepeer.payments.v1.PayeeDaemonCloseSessionRequest
	23, // 19: livepeer.payments.v1.PayeeDaemon.ListPendingRedemptions:input_type -> livepeer.payments.v1.ListPendingRedemptionsRequest
	26, // 20: livepeer.payments.v1.PayeeDaemon.GetRedemptionStatus:input_type -> livepeer.payments.v1.GetRedemptionStatusRequest
	4,  // 21: livepeer.payments.v1.PayeeDaemon.GetQuote:output_type -> livepeer.payments.v1.GetQuoteResponse
	6,  // 22: livepeer.payments.v1.PayeeDaemon.GetTicketParams:output_type -> livepeer.payments.v1.GetTicketParamsResponse
	9,  // 23: livepeer.payments.v1.PayeeDaemon.ListCapabilities:output_type -> livepeer.payments.v1.ListCapabilitiesResponse
	12, // 24: livepeer.payments.v1.PayeeDaemon.OpenSession:output_type -> livepeer.payments.v1.OpenSessionResponse
	14, // 25: livepeer.payments.v1.PayeeDaemon.ProcessPayment:output_type -> livepeer.payments.v1.ProcessPaymentResponse
	16, // 26: livepeer.payments.v1.PayeeDaemon.DebitBalance:output_type -> livepeer.payments.v1.DebitBalanceResponse
	18, // 27: livepeer.payments.v1.PayeeDaemon.SufficientBalance:output_type -> livepeer.payments.v1.SufficientBalanceResponse
	20, // 28: livepeer.payments.v1.PayeeDaemon.GetBalance:output_type -> livepeer.payments.v1.GetBalanceResponse
	22, // 29: livepeer.payments.v1.PayeeDaemon.CloseSession:output_type -> livepeer.payments.v1.PayeeDaemonCloseSessionResponse
	24, // 30: livepeer.payments.v1.PayeeDaemon.ListPendingRedemptions:output_type -> livepeer.payments.v1.ListPendingRedemptionsResponse
	27, // 31: livepeer.payments.v1.PayeeDaemon.GetRedemptionStatus:output_type -> livepeer.payments.v1.GetRedemptionStatusResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_livepeer_payments_v1_payee_daemon_proto_init() }
func file_livepeer_payments_v1_payee_daemon_proto_init() {
	if File_livepeer_payments_v1_payee_daemon_proto != nil {
		return
	}
	file_livepeer_payments_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_payee_daemon_proto_rawDesc), len(file_livepeer_payments_v1_payee_daemon_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_payments_v1_payee_daemon_proto_goTypes,
		DependencyIndexes: file_livepeer_payments_v1_payee_daemon_proto_depIdxs,
		EnumInfos:         file_livepeer_payments_v1_payee_daemon_proto_enumTypes,
		MessageInfos:      file_livepeer_payments_v1_payee_daemon_proto_msgTypes,
	}.Build()
	File_livepeer_payments_v1_payee_daemon_proto = out.File
	file_livepeer_payments_v1_payee_daemon_proto_goTypes = nil
	file_livepeer_payments_v1_payee_daemon_proto_depIdxs = nil
}
