// Livepeer Payments v1 — PayeeDaemon service.
//
// The PayeeDaemon runs next to a payee application (a specialized PayeeApp —
// e.g., a WorkerNode or a Livepeer orchestrator). It validates tickets,
// tracks per-sender balances, and redeems winning tickets on-chain via the
// TicketBroker.
//
// This service is mounted only when the daemon is started with
// `--mode=receiver`. Calls to it in sender mode return UNIMPLEMENTED.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: livepeer/payments/v1/payee_daemon.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayeeDaemon_GetQuote_FullMethodName               = "/livepeer.payments.v1.PayeeDaemon/GetQuote"
	PayeeDaemon_GetTicketParams_FullMethodName        = "/livepeer.payments.v1.PayeeDaemon/GetTicketParams"
	PayeeDaemon_ListCapabilities_FullMethodName       = "/livepeer.payments.v1.PayeeDaemon/ListCapabilities"
	PayeeDaemon_OpenSession_FullMethodName            = "/livepeer.payments.v1.PayeeDaemon/OpenSession"
	PayeeDaemon_ProcessPayment_FullMethodName         = "/livepeer.payments.v1.PayeeDaemon/ProcessPayment"
	PayeeDaemon_DebitBalance_FullMethodName           = "/livepeer.payments.v1.PayeeDaemon/DebitBalance"
	PayeeDaemon_SufficientBalance_FullMethodName      = "/livepeer.payments.v1.PayeeDaemon/SufficientBalance"
	PayeeDaemon_GetBalance_FullMethodName             = "/livepeer.payments.v1.PayeeDaemon/GetBalance"
	PayeeDaemon_CloseSession_FullMethodName           = "/livepeer.payments.v1.PayeeDaemon/CloseSession"
	PayeeDaemon_ListPendingRedemptions_FullMethodName = "/livepeer.payments.v1.PayeeDaemon/ListPendingRedemptions"
	PayeeDaemon_GetRedemptionStatus_FullMethodName    = "/livepeer.payments.v1.PayeeDaemon/GetRedemptionStatus"
)

// PayeeDaemonClient is the client API for PayeeDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayeeDaemonClient interface {
	// Return the TicketParams and per-offering pricing for a (sender, capability)
	// pair. The payer app queries this via its PayeeApp peer and hands the
	// result to its own PayerDaemon when starting a session. One TicketParams
	// covers every offering on the capability; per-offering prices are carried in
	// `offering_prices` and are what the payer checks against when billing.
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
	// Return canonical payee-issued TicketParams for an exact sender /
	// recipient / face-value tuple. This is the v3.0.1 replacement for the
	// cryptographic half of the old quote flow: pricing comes from manifest /
	// resolver, while the payee still owns recipientRandHash and expiry
	// generation.
	GetTicketParams(ctx context.Context, in *GetTicketParamsRequest, opts ...grpc.CallOption) (*GetTicketParamsResponse, error)
	// Return the daemon's full configured capability catalog. Drives the
	// worker's /capabilities HTTP response.
	ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error)
	// Open a payee-side session and bind authoritative pricing metadata to
	// `work_id`. The worker later seals the session's sender on the first
	// successful ProcessPayment.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	// Validate an incoming payment blob, credit the sender's balance by the
	// payment's expected value, and queue any winning tickets for redemption.
	// Requires a previously-opened session for `work_id`.
	ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...grpc.CallOption) (*ProcessPaymentResponse, error)
	// Debit session-priced work units from a (sender, work_id) balance after the
	// payee has actually done the work. Retries are idempotent by
	// (sender, work_id, debit_seq). Returns the new balance.
	DebitBalance(ctx context.Context, in *DebitBalanceRequest, opts ...grpc.CallOption) (*DebitBalanceResponse, error)
	// Check whether a (sender, work_id) balance covers a minimum number of
	// session-priced work units, without debiting.
	SufficientBalance(ctx context.Context, in *SufficientBalanceRequest, opts ...grpc.CallOption) (*SufficientBalanceResponse, error)
	// Get the current balance for a (sender, work_id) pair.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// Close and garbage-collect a work session. Any residual credit is
	// forfeited.
	CloseSession(ctx context.Context, in *PayeeDaemonCloseSessionRequest, opts ...grpc.CallOption) (*PayeeDaemonCloseSessionResponse, error)
	// Admin / observability: list winning tickets currently queued for
	// on-chain redemption.
	ListPendingRedemptions(ctx context.Context, in *ListPendingRedemptionsRequest, opts ...grpc.CallOption) (*ListPendingRedemptionsResponse, error)
	// Admin / observability: return the on-chain redemption status of a
	// previously-identified winning ticket.
	GetRedemptionStatus(ctx context.Context, in *GetRedemptionStatusRequest, opts ...grpc.CallOption) (*GetRedemptionStatusResponse, error)
}

type payeeDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPayeeDaemonClient(cc grpc.ClientConnInterface) PayeeDaemonClient {
	return &payeeDaemonClient{cc}
}

func (c *payeeDaemonClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) GetTicketParams(ctx context.Context, in *GetTicketParamsRequest, opts ...grpc.CallOption) (*GetTicketParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketParamsResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_GetTicketParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_ListCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...grpc.CallOption) (*ProcessPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessPaymentResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_ProcessPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) DebitBalance(ctx context.Context, in *DebitBalanceRequest, opts ...grpc.CallOption) (*DebitBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitBalanceResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_DebitBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) SufficientBalance(ctx context.Context, in *SufficientBalanceRequest, opts ...grpc.CallOption) (*SufficientBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SufficientBalanceResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_SufficientBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) CloseSession(ctx context.Context, in *PayeeDaemonCloseSessionRequest, opts ...grpc.CallOption) (*PayeeDaemonCloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayeeDaemonCloseSessionResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) ListPendingRedemptions(ctx context.Context, in *ListPendingRedemptionsRequest, opts ...grpc.CallOption) (*ListPendingRedemptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingRedemptionsResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_ListPendingRedemptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeeDaemonClient) GetRedemptionStatus(ctx context.Context, in *GetRedemptionStatusRequest, opts ...grpc.CallOption) (*GetRedemptionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedemptionStatusResponse)
	err := c.cc.Invoke(ctx, PayeeDaemon_GetRedemptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayeeDaemonServer is the server API for PayeeDaemon service.
// All implementations should embed UnimplementedPayeeDaemonServer
// for forward compatibility.
type PayeeDaemonServer interface {
	// Return the TicketParams and per-offering pricing for a (sender, capability)
	// pair. The payer app queries this via its PayeeApp peer and hands the
	// result to its own PayerDaemon when starting a session. One TicketParams
	// covers every offering on the capability; per-offering prices are carried in
	// `offering_prices` and are what the payer checks against when billing.
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	// Return canonical payee-issued TicketParams for an exact sender /
	// recipient / face-value tuple. This is the v3.0.1 replacement for the
	// cryptographic half of the old quote flow: pricing comes from manifest /
	// resolver, while the payee still owns recipientRandHash and expiry
	// generation.
	GetTicketParams(context.Context, *GetTicketParamsRequest) (*GetTicketParamsResponse, error)
	// Return the daemon's full configured capability catalog. Drives the
	// worker's /capabilities HTTP response.
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error)
	// Open a payee-side session and bind authoritative pricing metadata to
	// `work_id`. The worker later seals the session's sender on the first
	// successful ProcessPayment.
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	// Validate an incoming payment blob, credit the sender's balance by the
	// payment's expected value, and queue any winning tickets for redemption.
	// Requires a previously-opened session for `work_id`.
	ProcessPayment(context.Context, *ProcessPaymentRequest) (*ProcessPaymentResponse, error)
	// Debit session-priced work units from a (sender, work_id) balance after the
	// payee has actually done the work. Retries are idempotent by
	// (sender, work_id, debit_seq). Returns the new balance.
	DebitBalance(context.Context, *DebitBalanceRequest) (*DebitBalanceResponse, error)
	// Check whether a (sender, work_id) balance covers a minimum number of
	// session-priced work units, without debiting.
	SufficientBalance(context.Context, *SufficientBalanceRequest) (*SufficientBalanceResponse, error)
	// Get the current balance for a (sender, work_id) pair.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// Close and garbage-collect a work session. Any residual credit is
	// forfeited.
	CloseSession(context.Context, *PayeeDaemonCloseSessionRequest) (*PayeeDaemonCloseSessionResponse, error)
	// Admin / observability: list winning tickets currently queued for
	// on-chain redemption.
	ListPendingRedemptions(context.Context, *ListPendingRedemptionsRequest) (*ListPendingRedemptionsResponse, error)
	// Admin / observability: return the on-chain redemption status of a
	// previously-identified winning ticket.
	GetRedemptionStatus(context.Context, *GetRedemptionStatusRequest) (*GetRedemptionStatusResponse, error)
}

// UnimplementedPayeeDaemonServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayeeDaemonServer struct{}

func (UnimplementedPayeeDaemonServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedPayeeDaemonServer) GetTicketParams(context.Context, *GetTicketParamsRequest) (*GetTicketParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketParams not implemented")
}
func (UnimplementedPayeeDaemonServer) ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCapabilities not implemented")
}
func (UnimplementedPayeeDaemonServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedPayeeDaemonServer) ProcessPayment(context.Context, *ProcessPaymentRequest) (*ProcessPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedPayeeDaemonServer) DebitBalance(context.Context, *DebitBalanceRequest) (*DebitBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitBalance not implemented")
}
func (UnimplementedPayeeDaemonServer) SufficientBalance(context.Context, *SufficientBalanceRequest) (*SufficientBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SufficientBalance not implemented")
}
func (UnimplementedPayeeDaemonServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPayeeDaemonServer) CloseSession(context.Context, *PayeeDaemonCloseSessionRequest) (*PayeeDaemonCloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedPayeeDaemonServer) ListPendingRedemptions(context.Context, *ListPendingRedemptionsRequest) (*ListPendingRedemptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingRedemptions not implemented")
}
func (UnimplementedPayeeDaemonServer) GetRedemptionStatus(context.Context, *GetRedemptionStatusRequest) (*GetRedemptionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedemptionStatus not implemented")
}
func (UnimplementedPayeeDaemonServer) testEmbeddedByValue() {}

// UnsafePayeeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayeeDaemonServer will
// result in compilation errors.
type UnsafePayeeDaemonServer interface {
	mustEmbedUnimplementedPayeeDaemonServer()
}

func RegisterPayeeDaemonServer(s grpc.ServiceRegistrar, srv PayeeDaemonServer) {
	// If the following call panics, it indicates UnimplementedPayeeDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayeeDaemon_ServiceDesc, srv)
}

func _PayeeDaemon_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_GetTicketParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).GetTicketParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_GetTicketParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).GetTicketParams(ctx, req.(*GetTicketParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_ListCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).ListCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_ListCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_ProcessPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).ProcessPayment(ctx, req.(*ProcessPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_DebitBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).DebitBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_DebitBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).DebitBalance(ctx, req.(*DebitBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_SufficientBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SufficientBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).SufficientBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_SufficientBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).SufficientBalance(ctx, req.(*SufficientBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayeeDaemonCloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).CloseSession(ctx, req.(*PayeeDaemonCloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_ListPendingRedemptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRedemptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).ListPendingRedemptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_ListPendingRedemptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).ListPendingRedemptions(ctx, req.(*ListPendingRedemptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayeeDaemon_GetRedemptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedemptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeDaemonServer).GetRedemptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayeeDaemon_GetRedemptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeDaemonServer).GetRedemptionStatus(ctx, req.(*GetRedemptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayeeDaemon_ServiceDesc is the grpc.ServiceDesc for PayeeDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayeeDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.payments.v1.PayeeDaemon",
	HandlerType: (*PayeeDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _PayeeDaemon_GetQuote_Handler,
		},
		{
			MethodName: "GetTicketParams",
			Handler:    _PayeeDaemon_GetTicketParams_Handler,
		},
		{
			MethodName: "ListCapabilities",
			Handler:    _PayeeDaemon_ListCapabilities_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _PayeeDaemon_OpenSession_Handler,
		},
		{
			MethodName: "ProcessPayment",
			Handler:    _PayeeDaemon_ProcessPayment_Handler,
		},
		{
			MethodName: "DebitBalance",
			Handler:    _PayeeDaemon_DebitBalance_Handler,
		},
		{
			MethodName: "SufficientBalance",
			Handler:    _PayeeDaemon_SufficientBalance_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PayeeDaemon_GetBalance_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _PayeeDaemon_CloseSession_Handler,
		},
		{
			MethodName: "ListPendingRedemptions",
			Handler:    _PayeeDaemon_ListPendingRedemptions_Handler,
		},
		{
			MethodName: "GetRedemptionStatus",
			Handler:    _PayeeDaemon_GetRedemptionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/payments/v1/payee_daemon.proto",
}
