// Livepeer Payments v1 — shared types.
//
// These messages are a wire-compatible re-declaration of the payment-relevant
// portion of go-livepeer's `net/lp_rpc.proto`. Field numbers, tag numbers, and
// types are preserved byte-for-byte so that `livepeer.payments.v1.Payment`
// encodes identically to `net.Payment` from go-livepeer.
//
// See docs/design-docs/wire-compat.md for the compatibility contract and the
// round-trip test that enforces it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/payments/v1/types.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PriceInfo conveys pricing info for a unit of work.
//
// `pixelsPerUnit` is a historical name; the denominator is really just "work
// units" — pixels, tokens, seconds, or anything the consumer chooses. For wire
// compatibility the field name is preserved.
type PriceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price in wei per `pixels_per_unit` units of work.
	//
	// NOTE ON WIRE COMPAT: the proto field NAME differs from go-livepeer's
	// (`pricePerUnit` vs `price_per_unit`), but the field NUMBER is identical.
	// Proto encoding keys on the number, not the name, so bytes on the wire
	// remain compatible. The Go-generated field name is `PricePerUnit` in both
	// projects. See docs/design-docs/wire-compat.md.
	PricePerUnit int64 `protobuf:"varint,1,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	// Work units covered by `price_per_unit`. Setting `price_per_unit = 1` with
	// a larger `pixels_per_unit` lets pricing go finer than 1 wei per unit.
	PixelsPerUnit int64 `protobuf:"varint,2,opt,name=pixels_per_unit,json=pixelsPerUnit,proto3" json:"pixels_per_unit,omitempty"`
	// Capability this price applies to (uint32 capability ID, as in go-livepeer).
	// The daemon's RPC surface accepts string capability names and maps them to
	// this uint32 at the boundary.
	Capability uint32 `protobuf:"varint,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// Non-binary constraint this price applies to (e.g., a specific model id).
	Constraint    string `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceInfo) Reset() {
	*x = PriceInfo{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInfo) ProtoMessage() {}

func (x *PriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInfo.ProtoReflect.Descriptor instead.
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *PriceInfo) GetPricePerUnit() int64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *PriceInfo) GetPixelsPerUnit() int64 {
	if x != nil {
		return x.PixelsPerUnit
	}
	return 0
}

func (x *PriceInfo) GetCapability() uint32 {
	if x != nil {
		return x.Capability
	}
	return 0
}

func (x *PriceInfo) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

// TicketParams is the recipient-controlled portion of a ticket. The payee
// issues these to a payer during discovery (via `GetQuote`); the payer uses
// them verbatim when constructing tickets in a `TicketBatch`.
type TicketParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ETH address of the recipient.
	Recipient []byte `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Payout in wei if the ticket wins. Represented as big-endian bytes.
	FaceValue []byte `protobuf:"bytes,2,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Probability the ticket wins, scaled to the 256-bit win-probability field
	// (maxWinProb = 2^256 - 1). Big-endian bytes.
	WinProb []byte `protobuf:"bytes,3,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	// 32-byte keccak-256 hash commitment to a random number held by the recipient.
	RecipientRandHash []byte `protobuf:"bytes,4,opt,name=recipient_rand_hash,json=recipientRandHash,proto3" json:"recipient_rand_hash,omitempty"`
	// Seed the recipient uses to derive the random number corresponding to
	// `recipient_rand_hash`.
	Seed []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	// L1 block number after which this set of TicketParams is no longer valid.
	// Big-endian bytes.
	ExpirationBlock []byte `protobuf:"bytes,6,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	// Expiration parameters used at ticket-validation time.
	ExpirationParams *TicketExpirationParams `protobuf:"bytes,7,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketParams) Reset() {
	*x = TicketParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketParams) ProtoMessage() {}

func (x *TicketParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketParams.ProtoReflect.Descriptor instead.
func (*TicketParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *TicketParams) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *TicketParams) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *TicketParams) GetWinProb() []byte {
	if x != nil {
		return x.WinProb
	}
	return nil
}

func (x *TicketParams) GetRecipientRandHash() []byte {
	if x != nil {
		return x.RecipientRandHash
	}
	return nil
}

func (x *TicketParams) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *TicketParams) GetExpirationBlock() []byte {
	if x != nil {
		return x.ExpirationBlock
	}
	return nil
}

func (x *TicketParams) GetExpirationParams() *TicketExpirationParams {
	if x != nil {
		return x.ExpirationParams
	}
	return nil
}

// TicketSenderParams contains per-ticket nonce + signature values that the
// sender produces while creating a ticket batch.
type TicketSenderParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing counter that makes a ticket unique relative to a
	// given `recipient_rand_hash` in `TicketParams`.
	SenderNonce uint32 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	// Sender's ECDSA signature over the ticket hash.
	Sig           []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketSenderParams) Reset() {
	*x = TicketSenderParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketSenderParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketSenderParams) ProtoMessage() {}

func (x *TicketSenderParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketSenderParams.ProtoReflect.Descriptor instead.
func (*TicketSenderParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *TicketSenderParams) GetSenderNonce() uint32 {
	if x != nil {
		return x.SenderNonce
	}
	return 0
}

func (x *TicketSenderParams) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// TicketExpirationParams carries the Livepeer "round" and associated block
// hash used to validate ticket freshness against the protocol round state.
type TicketExpirationParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Livepeer protocol round during which the tickets were created.
	CreationRound int64 `protobuf:"varint,1,opt,name=creation_round,json=creationRound,proto3" json:"creation_round,omitempty"`
	// Block hash associated with `creation_round`.
	CreationRoundBlockHash []byte `protobuf:"bytes,2,opt,name=creation_round_block_hash,json=creationRoundBlockHash,proto3" json:"creation_round_block_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TicketExpirationParams) Reset() {
	*x = TicketExpirationParams{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketExpirationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketExpirationParams) ProtoMessage() {}

func (x *TicketExpirationParams) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketExpirationParams.ProtoReflect.Descriptor instead.
func (*TicketExpirationParams) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *TicketExpirationParams) GetCreationRound() int64 {
	if x != nil {
		return x.CreationRound
	}
	return 0
}

func (x *TicketExpirationParams) GetCreationRoundBlockHash() []byte {
	if x != nil {
		return x.CreationRoundBlockHash
	}
	return nil
}

// Payment is the on-the-wire payment message. One `Payment` can carry many
// tickets (one per entry in `ticket_sender_params`) so a payer can cover a
// whole segment / job / session in a single wire message.
type Payment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient-controlled ticket parameters. Stays the same across all tickets
	// in this payment.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// ETH address of the sender.
	Sender []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Shared expiration params for all tickets in this payment.
	ExpirationParams *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	// Per-ticket sender parameters (nonce + signature). One entry per ticket.
	TicketSenderParams []*TicketSenderParams `protobuf:"bytes,4,rep,name=ticket_sender_params,json=ticketSenderParams,proto3" json:"ticket_sender_params,omitempty"`
	// Payer's last-known price for this work. Used by the payee to detect stale
	// clients and trigger a re-quote.
	ExpectedPrice *PriceInfo `protobuf:"bytes,5,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Payment) GetTicketParams() *TicketParams {
	if x != nil {
		return x.TicketParams
	}
	return nil
}

func (x *Payment) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Payment) GetExpirationParams() *TicketExpirationParams {
	if x != nil {
		return x.ExpirationParams
	}
	return nil
}

func (x *Payment) GetTicketSenderParams() []*TicketSenderParams {
	if x != nil {
		return x.TicketSenderParams
	}
	return nil
}

func (x *Payment) GetExpectedPrice() *PriceInfo {
	if x != nil {
		return x.ExpectedPrice
	}
	return nil
}

var File_livepeer_payments_v1_types_proto protoreflect.FileDescriptor

const file_livepeer_payments_v1_types_proto_rawDesc = "" +
	"\n" +
	" livepeer/payments/v1/types.proto\x12\x14livepeer.payments.v1\"\x99\x01\n" +
	"\tPriceInfo\x12$\n" +
	"\x0eprice_per_unit\x18\x01 \x01(\x03R\fpricePerUnit\x12&\n" +
	"\x0fpixels_per_unit\x18\x02 \x01(\x03R\rpixelsPerUnit\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\rR\n" +
	"capability\x12\x1e\n" +
	"\n" +
	"constraint\x18\x04 \x01(\tR\n" +
	"constraint\"\xb0\x02\n" +
	"\fTicketParams\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\fR\trecipient\x12\x1d\n" +
	"\n" +
	"face_value\x18\x02 \x01(\fR\tfaceValue\x12\x19\n" +
	"\bwin_prob\x18\x03 \x01(\fR\awinProb\x12.\n" +
	"\x13recipient_rand_hash\x18\x04 \x01(\fR\x11recipientRandHash\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\fR\x04seed\x12)\n" +
	"\x10expiration_block\x18\x06 \x01(\fR\x0fexpirationBlock\x12Y\n" +
	"\x11expiration_params\x18\a \x01(\v2,.livepeer.payments.v1.TicketExpirationParamsR\x10expirationParams\"I\n" +
	"\x12TicketSenderParams\x12!\n" +
	"\fsender_nonce\x18\x01 \x01(\rR\vsenderNonce\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"z\n" +
	"\x16TicketExpirationParams\x12%\n" +
	"\x0ecreation_round\x18\x01 \x01(\x03R\rcreationRound\x129\n" +
	"\x19creation_round_block_hash\x18\x02 \x01(\fR\x16creationRoundBlockHash\"\xe9\x02\n" +
	"\aPayment\x12G\n" +
	"\rticket_params\x18\x01 \x01(\v2\".livepeer.payments.v1.TicketParamsR\fticketParams\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12Y\n" +
	"\x11expiration_params\x18\x03 \x01(\v2,.livepeer.payments.v1.TicketExpirationParamsR\x10expirationParams\x12Z\n" +
	"\x14ticket_sender_params\x18\x04 \x03(\v2(.livepeer.payments.v1.TicketSenderParamsR\x12ticketSenderParams\x12F\n" +
	"\x0eexpected_price\x18\x05 \x01(\v2\x1f.livepeer.payments.v1.PriceInfoR\rexpectedPriceB\x83\x02\n" +
	"\x18com.livepeer.payments.v1B\n" +
	"TypesProtoP\x01Zigithub.com/Cloud-SPE/livepeer-modules-project/payment-daemon/proto/gen/go/livepeer/payments/v1;paymentsv1\xa2\x02\x03LPX\xaa\x02\x14Livepeer.Payments.V1\xca\x02\x14Livepeer\\Payments\\V1\xe2\x02 Livepeer\\Payments\\V1\\GPBMetadata\xea\x02\x16Livepeer::Payments::V1b\x06proto3"

var (
	file_livepeer_payments_v1_types_proto_rawDescOnce sync.Once
	file_livepeer_payments_v1_types_proto_rawDescData []byte
)

func file_livepeer_payments_v1_types_proto_rawDescGZIP() []byte {
	file_livepeer_payments_v1_types_proto_rawDescOnce.Do(func() {
		file_livepeer_payments_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_types_proto_rawDesc), len(file_livepeer_payments_v1_types_proto_rawDesc)))
	})
	return file_livepeer_payments_v1_types_proto_rawDescData
}

var file_livepeer_payments_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_livepeer_payments_v1_types_proto_goTypes = []any{
	(*PriceInfo)(nil),              // 0: livepeer.payments.v1.PriceInfo
	(*TicketParams)(nil),           // 1: livepeer.payments.v1.TicketParams
	(*TicketSenderParams)(nil),     // 2: livepeer.payments.v1.TicketSenderParams
	(*TicketExpirationParams)(nil), // 3: livepeer.payments.v1.TicketExpirationParams
	(*Payment)(nil),                // 4: livepeer.payments.v1.Payment
}
var file_livepeer_payments_v1_types_proto_depIdxs = []int32{
	3, // 0: livepeer.payments.v1.TicketParams.expiration_params:type_name -> livepeer.payments.v1.TicketExpirationParams
	1, // 1: livepeer.payments.v1.Payment.ticket_params:type_name -> livepeer.payments.v1.TicketParams
	3, // 2: livepeer.payments.v1.Payment.expiration_params:type_name -> livepeer.payments.v1.TicketExpirationParams
	2, // 3: livepeer.payments.v1.Payment.ticket_sender_params:type_name -> livepeer.payments.v1.TicketSenderParams
	0, // 4: livepeer.payments.v1.Payment.expected_price:type_name -> livepeer.payments.v1.PriceInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_livepeer_payments_v1_types_proto_init() }
func file_livepeer_payments_v1_types_proto_init() {
	if File_livepeer_payments_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_types_proto_rawDesc), len(file_livepeer_payments_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livepeer_payments_v1_types_proto_goTypes,
		DependencyIndexes: file_livepeer_payments_v1_types_proto_depIdxs,
		MessageInfos:      file_livepeer_payments_v1_types_proto_msgTypes,
	}.Build()
	File_livepeer_payments_v1_types_proto = out.File
	file_livepeer_payments_v1_types_proto_goTypes = nil
	file_livepeer_payments_v1_types_proto_depIdxs = nil
}
